/**
 * Prescription Controller
 * Handles prescription CRUD operations and safety validations using OOP.
 */

import { Request, Response } from 'express';
import { prisma } from '../config/db';
import { EPrescription } from '../services/oop/MedicalRecord';

/**
 * Creates and validates a new E-Prescription using OOP concepts.
 */
export const createPrescription = async (req: Request, res: Response) => {
    try {
        const { appointmentId, patientId, patientName, doctorId, doctorName, department, date, medications, notes, safetyFlagged } = req.body;

        // 1. Instantiate the EPrescription class (OOP concept)
        const newPrescriptionDoc = new EPrescription(
            '', // ID generated by DB
            patientId,
            doctorName,
            date,
            appointmentId,
            department,
            medications,
            notes,
            safetyFlagged
        );

        // 2. Validate the document using polymorphic method call
        if (!newPrescriptionDoc.validate()) {
            res.status(400).json({ message: 'Invalid prescription: medications list cannot be empty.' });
            return;
        }

        // 3. Optional: Run deep interaction validation if there are multiple medications
        const allInteractions = await prisma.drugInteraction.findMany({});
        const safetyCheck = newPrescriptionDoc.checkSafetyInteractions(allInteractions);

        // 4. Save to MySQL via Prisma
        const createdRecord = await prisma.prescription.create({
            data: {
                appointmentId,
                patientId,
                patientName,
                doctorId,
                doctorName,
                department,
                date,
                medications: JSON.stringify(medications),
                notes,
                safetyFlagged: safetyFlagged || !safetyCheck.isSafe
            }
        });

        res.json({
            prescription: createdRecord,
            safetyCheck
        });
    } catch (err: any) {
        res.status(500).json({ message: err.message });
    }
};

/**
 * Retrieves all prescriptions issued to a patient.
 */
export const getPatientPrescriptions = async (req: Request, res: Response) => {
    try {
        const { patientId } = req.params;
        const records = await prisma.prescription.findMany({
            where: { patientId },
            orderBy: { createdAt: 'desc' }
        });

        // Parse JSON strings back into structured array objects before sending
        const formattedRecords = records.map(rec => ({
            ...rec,
            medications: JSON.parse(rec.medications)
        }));

        res.json(formattedRecords);
    } catch (err: any) {
        res.status(500).json({ message: err.message });
    }
};

/**
 * Retrieves all prescriptions issued by a doctor.
 */
export const getDoctorPrescriptions = async (req: Request, res: Response) => {
    try {
        const { doctorId } = req.params;
        const records = await prisma.prescription.findMany({
            where: { doctorId },
            orderBy: { createdAt: 'desc' }
        });

        const formattedRecords = records.map(rec => ({
            ...rec,
            medications: JSON.parse(rec.medications)
        }));

        res.json(formattedRecords);
    } catch (err: any) {
        res.status(500).json({ message: err.message });
    }
};
